// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs61EmycN2z0f_D1iRBHiwTcN1dlqLaCw',
    appId: '1:225035134736:web:f1f2ff3c5bda48c2216795',
    messagingSenderId: '225035134736',
    projectId: 'kiln-pilot',
    authDomain: 'kiln-pilot.firebaseapp.com',
    storageBucket: 'kiln-pilot.firebasestorage.app',
    measurementId: 'G-1ZQBKEP0R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8tB4K-cDnb-suEAJL8iTAxJvRxqnIUUs',
    appId: '1:225035134736:android:2e6b2586c7e351e4216795',
    messagingSenderId: '225035134736',
    projectId: 'kiln-pilot',
    storageBucket: 'kiln-pilot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7hCsK32GUMh1yoGMB9FuiH5kQ5hZ41dY',
    appId: '1:225035134736:ios:0573cd8bb8cce780216795',
    messagingSenderId: '225035134736',
    projectId: 'kiln-pilot',
    storageBucket: 'kiln-pilot.firebasestorage.app',
    iosBundleId: 'com.harentortoise.kilnpilot',
  );

}